spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/system_user?allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    password:
  cache:
    # 缓存类型
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true
      # 允许使用缓存前缀，
      use-key-prefix: true
      # 缓存前缀，没有设置使用注解的缓存名称(value)作为前缀，和注解的key用双冒号::拼接组成完整缓存key
      key-prefix: 'admin:'
  mail:
    host: smtp.163.com
    port: 465
    username: yjxbzcl@163.com
    password: UJuDm3BEwmiFc2KN # 使用授权码
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true # 启用SMTP认证
          ssl:
            enable: true # 启用SSL加密
          connectiontimeout: 5000 # 连接超时时间
          timeout: 5000 # 读取超时时间
          writetimeout: 5000 # 写入超时时间

mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false

knife4j:
  enable: true
  swagger-ui:
    enable: true